spring:
  application:
    name: campaign-touch
  datasource:
    url: jdbc:postgresql://localhost:5432/campaign_touch
    username: campaign_touch
    password: campaign_touch
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
